### PR TITLE
feat: enable Clone, Eq, PartialEq and Debug macro for RegistryAuth

### PR DESCRIPTION
**Pull request by Xynnn007**
This is useful for downstream crates to write related tests

Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>

### CODE REVIEW

**Review by flavio — APPROVED** [review]
LGTM

**Review by flavio — CHANGES_REQUESTED** [review]
Can you please look into the failing test please?

**Comment by Xynnn007** [comment]
> Can you please look into the failing test please?

This problem seems not related to this PR. I'm going to open an issue

**Comment by Xynnn007** [comment]
refer to https://github.com/krustlet/oci-distribution/issues/49

**Comment by flavio** [comment]
Thanks @Xynnn007. Let's merge this PR in the meantime

**Pull request merged**
