### PR TITLE
bump to hyperx 1.3

### PR DESCRIPTION
**Pull request by bacongobbler**
Needed to fix the `chrono`-related security issues - hyperx 0.13 was released back in January 2019.

Note: this is pending a change upstream to be [merged for hyperx 1.3 support](https://github.com/KeenS/www-authenticate/pull/5). Once that's merged I can stop cargo from pointing at my local git repository, which is necessary to publish oci-distribution.

### CODE REVIEW

**Comment by radu-matei** [comment]
Is there anything left before we can merge this?

**Comment by thomastaylor312** [comment]
We need a new version of www-authenticate to be cut so we can pull it in here. It is still pulling in from @bacongobbler's branch

**Comment by bacongobbler** [comment]
Due to inactivity and how little code is involved, I imported it directly into oci-distribution as we have done with other crates.

**Comment by bacongobbler** [comment]
yay we're green again!!!

**Review by thomastaylor312 — APPROVED** [review]

**Pull request merged**
