### PR TITLE
Allow to use trust-dns

### PR DESCRIPTION
**Pull request by astoycos**
Add options to oci-distrobution to use
non local DNS, mainly for when
running embedded in a docker container.

### CODE REVIEW

**Comment by astoycos** [comment]
I don't _think_ the failing CI is part of this :)

**Comment by astoycos** [comment]
If I get a chance I'll investigate further

**Comment by thomastaylor312** [comment]
I don't think the cargo deny is related, but the `build` test might be. I'm a bit busy this week but will try to get to debugging it a bit

**Comment by astoycos** [comment]
Ran this all locally and things were working, pushed again to re-trigger actions

**Comment by astoycos** [comment]
```
failures:

---- client::test::test_platform_resolution stdout ----
thread 'client::test::test_platform_resolution' panicked at 'Couldn't pull manifest: RequestError(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("auth.docker.io")), port: None, path: "/token", query: Some("scope=repository%3Alibrary%2Fhello-world%3Apull&service=registry.docker.io"), fragment: None }, source: hyper::Error(IncompleteMessage) })', src/client.rs:2227:14
error: test failed, to rerun pass '--lib'
```

Was the error in the unit tests the first time

**Comment by flavio** [comment]
@astoycos  Sorry for the late response. I've looked into the failures and fixed them with some commits.

I'll let the test run and, if everything is green, I'll merge the PR

**Comment by flavio** [comment]
All green!

**Comment by astoycos** [comment]
Thanks @flavio!

**Pull request merged**
