### PR TITLE
Remove manifest list from MIME Accept header

### PR DESCRIPTION
**Pull request by kflansburg**
We pass a list of accepted MIME types when pulling manifests, but then we immediately reject anything other than `application/vnd.docker.distribution.manifest.v2+json` when validating the response on:
https://github.com/krustlet/oci-distribution/blob/0e5373e99c910ffd1261ace7e1b732036dc7784a/src/client.rs#L548

This change removes the list type which we are incapable of parsing. As a result, registries which can serve manifest lists (like DockerHub) will return a single manifest instead (presumably for `amd64`?). If we have a strong opinion in the future about which manifest to use from the list, we can implement proper parsing for these manifest lists.

### CODE REVIEW

**Comment by thomastaylor312** [comment]
I am not confident enough with my OCI knowledge to know if this change is ok. @flavio do you have any insight here?

**Comment by rickrain** [comment]
Would really like to see this ( or #3 ) merged in soon. This one is perfect for now IMO and wouldn't break anything since it (`manifest.list`) was not supported anyway.

**Review by flavio — APPROVED** [review]
Sorry for the delay, I think it's safe to merge this PR. I'll also take a closer look at #3

**Comment by flavio** [comment]
@kflansburg could you please add your signature to commit 94a3993215aae7658d36498cd3f9cb73c61d3502? This is required to make the DCO check green

**Comment by kflansburg** [comment]
> @kflansburg could you please add your signature to commit [94a3993](https://github.com/krustlet/oci-distribution/commit/94a3993215aae7658d36498cd3f9cb73c61d3502)? This is required to make the DCO check green

Done

**Pull request merged**
