### PR TITLE
move www-authenticate to a sub-crate

### PR DESCRIPTION
**Pull request by flavio**
Move the `www-authenticate` to a dedicated sub-crate.

This reduces the number of warnings generated at build time.

On top of that, other small fixes have been done to address the clippy warnings that became visible.

Fixes issue #7

### CODE REVIEW

**Comment by thomastaylor312** [comment]
@flavio So I just realized I may have screwed up. I don’t know if we can publish the crate anymore if we make it a subcrate. Can you try a `cargo publish --dry-run` on the main oci-distribution crate and see if it gives you a warning about unpublished crates? If it is, I apologize for sending you down this rabbit hole

**Comment by flavio** [comment]
ah! you're right, this is not going to fly:

```console
$ cargo publish --dry-run 
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `www-authenticate` does not specify a version
Note: The published dependency will use the version from crates.io,
```

What about:
  * fork the `www-authenticate` repository under the krustlet organization
  * add your patches inside of it
  * tag a new version of it
  * update `oci-distribution` crate to get the dependency from our git fork, using the tag we just created

This would also have the advantage of making more evident the changes we've done to the original `www-authenticate` crate.

Could that work?

**Comment by flavio** [comment]
I fear this would not work either according to the rust docs (thanks @ereslibre for pointing that out): https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations

I fear the only solution would be to create a fork of www-authenticate with our changes, and then publish that with a different name on crates.io

**Comment by thomastaylor312** [comment]
Yeah we can't publish with the same name. I think we just keep it as is for now and then update it when the maintainer eventually cuts another version

**Review by bacongobbler — APPROVED** [review]

**Comment by bacongobbler** [comment]
I agree with @thomastaylor312's thoughts. The only reason the crate was pulled in here was because the project [appears to be unmaintained](https://github.com/KeenS/www-authenticate/issues/4#issuecomment-832889092) and we haven't seen a release since 2018.

**Comment by thomastaylor312** [comment]
@bacongobbler @flavio  Should we go ahead and close this PR then?

**Comment by flavio** [comment]
Yep, closing. I'll file a PR against the original repo and see how the maintainer reacts to it

**Pull request closed without merging**
